export const GET_ALLPRODUCTS_SUCCESS = "GET_ALLPRODUCTS_SUCCESS"
export const GET_ALLPRODUCTS_FAIL = "GET_ALLPRODUCTS_FAIL"
export const LOADINGPRODUCTS = 'LOADINGPRODUCTS'
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS"
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL"
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS"
export const EDIT_PRODUCT_FAIL = "EDIT_PRODUCT_FAIL"
export const GET_ONEPRODUCTS_SUCCESS = "GET_ONEPRODUCTS_SUCCESS"
export const GET_ONEPRODUCTS_FAIL = "GET_ONEPRODUCTS_FAIL"

export const DELETE_ONEPRODUCTS_SUCCESS = "DELETE_ONEPRODUCTS_SUCCESS"
export const DELETE_ONEPRODUCTS_FAIL = "DELETE_ONEPRODUCTS_FAIL"

