export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"

export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const GET_CURRENT_SUCCESS = "GET_CURRENT_SUCCESS"
export const GET_CURRENT_FAIL = "GET_CURRENT_FAIL"

export const LOGOUT="LOGOUT"